-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 21, 2020 at 10:45 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `startech`
--
DROP DATABASE IF EXISTS startech;
CREATE DATABASE IF NOT EXISTS startech;
USE startech;
-- --------------------------------------------------------

--
-- Table structure for table `desktop`
--

CREATE TABLE `desktop` (
  `id` int(11) NOT NULL,
  `Name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SKU` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Image` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Specification` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Price` float NOT NULL,
  `Regular Price` float NOT NULL,
  `Status` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Product Code` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Brand` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Features` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` date DEFAULT NULL,
  `created_at` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `desktop`
--

INSERT INTO `desktop` (`id`, `Name`, `SKU`, `Image`, `Description`, `Specification`, `Price`, `Regular Price`, `Status`, `Product Code`, `Brand`, `Features`, `updated_at`, `created_at`) VALUES
(1, 'Asus AIO A4321UKH Core i5 7th Gen PC', NULL, 'desktop/4.jpg', 'Asus AIO A4321UKH all in one PC with Intel core i5-7400 processor having 3.00 GHz base and turbo 3.50 GHz frequency, 6M Cache and 4GB DDR4 RAM is an essential business desktop that also contains 1TB 7200RPM of SATA storage to ensure greater workability. It has 19.5\" HD wide screen LED backlight display and other component includes USB keyboard & optical mouse. In addition, it has Intel HD 630 graphics, Endless operating system, 1 MP webcam and DVD writer. This business-class performance, security and management in a space-saving design comes with 01 year of warranty.\r\n\r\nBest price is available at Star Tech for Asus all in one PC with world class expert solutions. We operate in all the major cities such as Rangpur, Dhaka, Chattagram, Khulna & Sylhet. Now you can order online to have your desired all in one PC for your business in any place in Bangladesh.', 'Basic Information\r\nProcessor	Intel® Core™ i5-7400 (3.00 GHz up to 3.50 GHz, 6 MB SmartCache, Cores: 4, Threads: 4\r\nMotherboard	Intel® H110\r\nRAM	4 GB DDR4 2400MHz\r\nGraphics Card	Intel® HD Graphics 630\r\nStorage	1TB 7200 RPM\r\nMonitor	19.5\" HD Monitor\r\nNetwork & Wireless Connectivity	802.11 a/b/g/n/ac, 802.11 a/b/g/n\r\nInput Devices\r\nKeyboard	USB Optical Keyboard\r\nMouse	USB Optical Mouse\r\nOptical Drive	Tray-in DVD RW 8X (Optional)\r\nWarranty Information\r\nWarranty	01 Year Warranty', 56, 56, 'Out of stock', 'ASU09238', 'ASUS', 'Model: Asus AIO A4321UKH\r\nIntel® Core i5-7400 (3.00 GHz up to 3.50 GHz)\r\n4 GB DDR4 Ram\r\n1 TB HDD\r\n19.5\" HD Monitor', '0000-00-00', '0000-00-00'),
(2, 'Asus AIO A4321UKH Core i5 7th Gen PC', NULL, 'desktop/2.jpg', 'Asus AIO A4321UKH all in one PC with Intel core i5-7400 processor having 3.00 GHz base and turbo 3.50 GHz frequency, 6M Cache and 4GB DDR4 RAM is an essential business desktop that also contains 1TB 7200RPM of SATA storage to ensure greater workability. It has 19.5\" HD wide screen LED backlight display and other component includes USB keyboard & optical mouse. In addition, it has Intel HD 630 graphics, Endless operating system, 1 MP webcam and DVD writer. This business-class performance, security and management in a space-saving design comes with 01 year of warranty.\r\n\r\nBest price is available at Star Tech for Asus all in one PC with world class expert solutions. We operate in all the major cities such as Rangpur, Dhaka, Chattagram, Khulna & Sylhet. Now you can order online to have your desired all in one PC for your business in any place in Bangladesh.', 'Basic Information\r\nProcessor	Intel® Core™ i5-7400 (3.00 GHz up to 3.50 GHz, 6 MB SmartCache, Cores: 4, Threads: 4\r\nMotherboard	Intel® H110\r\nRAM	4 GB DDR4 2400MHz\r\nGraphics Card	Intel® HD Graphics 630\r\nStorage	1TB 7200 RPM\r\nMonitor	19.5\" HD Monitor\r\nNetwork & Wireless Connectivity	802.11 a/b/g/n/ac, 802.11 a/b/g/n\r\nInput Devices\r\nKeyboard	USB Optical Keyboard\r\nMouse	USB Optical Mouse\r\nOptical Drive	Tray-in DVD RW 8X (Optional)\r\nWarranty Information\r\nWarranty	01 Year Warranty', 56000, 56000, 'IN STOCk', 'ASU99885', 'ASUS', 'Model: Asus AIO A4321UKH\r\nIntel® Core i5-7400 (3.00 GHz up to 3.50 GHz)\r\n4 GB DDR4 Ram\r\n1 TB HDD\r\n19.5\" HD Monitor', NULL, NULL),
(3, 'Asus AIO A4321UKH Core i5 7th Gen PC', NULL, 'desktop/1.jpg', 'Asus AIO A4321UKH all in one PC with Intel core i5-7400 processor having 3.00 GHz base and turbo 3.50 GHz frequency, 6M Cache and 4GB DDR4 RAM is an essential business desktop that also contains 1TB 7200RPM of SATA storage to ensure greater workability. It has 19.5\" HD wide screen LED backlight display and other component includes USB keyboard & optical mouse. In addition, it has Intel HD 630 graphics, Endless operating system, 1 MP webcam and DVD writer. This business-class performance, security and management in a space-saving design comes with 01 year of warranty.\r\n\r\nBest price is available at Star Tech for Asus all in one PC with world class expert solutions. We operate in all the major cities such as Rangpur, Dhaka, Chattagram, Khulna & Sylhet. Now you can order online to have your desired all in one PC for your business in any place in Bangladesh.', 'Basic Information\r\nProcessor	Intel® Core™ i5-7400 (3.00 GHz up to 3.50 GHz, 6 MB SmartCache, Cores: 4, Threads: 4\r\nMotherboard	Intel® H110\r\nRAM	4 GB DDR4 2400MHz\r\nGraphics Card	Intel® HD Graphics 630\r\nStorage	1TB 7200 RPM\r\nMonitor	19.5\" HD Monitor\r\nNetwork & Wireless Connectivity	802.11 a/b/g/n/ac, 802.11 a/b/g/n\r\nInput Devices\r\nKeyboard	USB Optical Keyboard\r\nMouse	USB Optical Mouse\r\nOptical Drive	Tray-in DVD RW 8X (Optional)\r\nWarranty Information\r\nWarranty	01 Year Warranty', 56, 56, 'Out of stock', 'ASU09238', 'ASUS', 'Model: Asus AIO A4321UKH\r\nIntel® Core i5-7400 (3.00 GHz up to 3.50 GHz)\r\n4 GB DDR4 Ram\r\n1 TB HDD\r\n19.5\" HD Monitor', '0000-00-00', '0000-00-00'),
(4, 'Asus AIO A4321UKH Core i5 7th Gen PC', NULL, 'desktop/3.jpg', 'Asus AIO A4321UKH all in one PC with Intel core i5-7400 processor having 3.00 GHz base and turbo 3.50 GHz frequency, 6M Cache and 4GB DDR4 RAM is an essential business desktop that also contains 1TB 7200RPM of SATA storage to ensure greater workability. It has 19.5\" HD wide screen LED backlight display and other component includes USB keyboard & optical mouse. In addition, it has Intel HD 630 graphics, Endless operating system, 1 MP webcam and DVD writer. This business-class performance, security and management in a space-saving design comes with 01 year of warranty.\r\n\r\nBest price is available at Star Tech for Asus all in one PC with world class expert solutions. We operate in all the major cities such as Rangpur, Dhaka, Chattagram, Khulna & Sylhet. Now you can order online to have your desired all in one PC for your business in any place in Bangladesh.', 'Basic Information\r\nProcessor	Intel® Core™ i5-7400 (3.00 GHz up to 3.50 GHz, 6 MB SmartCache, Cores: 4, Threads: 4\r\nMotherboard	Intel® H110\r\nRAM	4 GB DDR4 2400MHz\r\nGraphics Card	Intel® HD Graphics 630\r\nStorage	1TB 7200 RPM\r\nMonitor	19.5\" HD Monitor\r\nNetwork & Wireless Connectivity	802.11 a/b/g/n/ac, 802.11 a/b/g/n\r\nInput Devices\r\nKeyboard	USB Optical Keyboard\r\nMouse	USB Optical Mouse\r\nOptical Drive	Tray-in DVD RW 8X (Optional)\r\nWarranty Information\r\nWarranty	01 Year Warranty', 56, 56, 'Out of stock', 'ASU09238', 'ASUS', 'Model: Asus AIO A4321UKH\r\nIntel® Core i5-7400 (3.00 GHz up to 3.50 GHz)\r\n4 GB DDR4 Ram\r\n1 TB HDD\r\n19.5\" HD Monitor', '0000-00-00', '0000-00-00'),
(5, 'Asus AIO A4321UKH Core i5 7th Gen PC', NULL, 'desktop/1.jpg', 'Asus AIO A4321UKH all in one PC with Intel core i5-7400 processor having 3.00 GHz base and turbo 3.50 GHz frequency, 6M Cache and 4GB DDR4 RAM is an essential business desktop that also contains 1TB 7200RPM of SATA storage to ensure greater workability. It has 19.5\" HD wide screen LED backlight display and other component includes USB keyboard & optical mouse. In addition, it has Intel HD 630 graphics, Endless operating system, 1 MP webcam and DVD writer. This business-class performance, security and management in a space-saving design comes with 01 year of warranty.\r\n\r\nBest price is available at Star Tech for Asus all in one PC with world class expert solutions. We operate in all the major cities such as Rangpur, Dhaka, Chattagram, Khulna & Sylhet. Now you can order online to have your desired all in one PC for your business in any place in Bangladesh.', 'Basic Information\r\nProcessor	Intel® Core™ i5-7400 (3.00 GHz up to 3.50 GHz, 6 MB SmartCache, Cores: 4, Threads: 4\r\nMotherboard	Intel® H110\r\nRAM	4 GB DDR4 2400MHz\r\nGraphics Card	Intel® HD Graphics 630\r\nStorage	1TB 7200 RPM\r\nMonitor	19.5\" HD Monitor\r\nNetwork & Wireless Connectivity	802.11 a/b/g/n/ac, 802.11 a/b/g/n\r\nInput Devices\r\nKeyboard	USB Optical Keyboard\r\nMouse	USB Optical Mouse\r\nOptical Drive	Tray-in DVD RW 8X (Optional)\r\nWarranty Information\r\nWarranty	01 Year Warranty', 56, 56, 'Out of stock', 'ASU09238', 'ASUS', 'Model: Asus AIO A4321UKH\r\nIntel® Core i5-7400 (3.00 GHz up to 3.50 GHz)\r\n4 GB DDR4 Ram\r\n1 TB HDD\r\n19.5\" HD Monitor', '0000-00-00', '0000-00-00');

-- --------------------------------------------------------

--
-- Table structure for table `laptop`
--

CREATE TABLE `laptop` (
  `id` int(11) NOT NULL,
  `Name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `SKU` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Image` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Specification` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Price` float NOT NULL,
  `Regular Price` float NOT NULL,
  `Status` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Product Code` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Brand` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `Features` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` date DEFAULT NULL,
  `created_at` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `laptop`
--

INSERT INTO `laptop` (`id`, `Name`, `SKU`, `Image`, `Description`, `Specification`, `Price`, `Regular Price`, `Status`, `Product Code`, `Brand`, `Features`, `updated_at`, `created_at`) VALUES
(1, 'ASUS F571LI Core i5 10th Gen NVIDIA 1650 Ti Graphics 15.6\" FHD Gaming Laptop with Windows 10', NULL, 'laptop/asus1.jpg', '.\r\n\r\nThis multi function extreme durable device comes with 02 years International Limited Warranty (Terms & condition Apply As Per Asus)', 'Basic Information\r\nProcessor	Intel Core i5-10300H Processor (8M Cache, 2.5 GHz up to 4.5 GHz)\r\nDisplay	15.6\" FHD (1920x1080) LED-backlit (16:9), 60Hz Anti-Glare Panel with 45% NTSC Display with wide 178° viewing angles\r\nMemory	8GB DDR4 2666MHz RAM (4GB x 2)\r\nStorage	1TB HDD\r\nGraphics	Nvidia GeForce GTX 1650Ti with 4GB GDDR6 Graphics\r\nOperating System	Windows 10\r\nBattery	3 -Cell 42 Wh Polymer Battery\r\nAdapter	Plug type :ø4.5 (mm)\r\nOutput :\r\n19 V DC, 7.89 A, 150 W\r\nInput :\r\n100 -240 V AC, 50/60 Hz universal\r\nSpecial Feature	Back-lit Keyboard\r\nFinger Print Sensor\r\nInput Devices\r\nKeyboard	Back-lit Keyboard\r\nWebCam	HD\r\nNetwork & Wireless Connectivity\r\nWi-Fi	Integrated Wi-Fi 6 (802.11 ax (2x2)\r\nBluetooth	Bluetooth 5.0\r\nPorts, Connectors & Slots\r\nUSB (s)	1 x Type-C USB 3.0 (USB 3.1 Gen 1)\r\n1 x Type-A USB 3.0 (USB 3.1 Gen 1)\r\n2 x USB 2.0 port(s)\r\n1 x RJ45 LAN jack for LAN insert\r\nHDMI	1 x HDMI\r\nAudio Jack Combo	1 x Combo audio jack\r\nExtra RAM Slot	Yes (Up to max.20GB)\r\nExtra M.2 Slot	Yes\r\nSupported SSD Type	M.2 NVMe\r\nPhysical Specification\r\nDimensions (W x D x H)	359 x 248 x 21.9 mm\r\nWeight	2.14 g with battery\r\nColor(s)	Star Black\r\nWarranty\r\nManufacturing Warranty	02 Year International Limited Warranty (Terms & condition Apply As Per Asus)', 90000, 94000, 'IN STOCK', 'ASULP88774', 'Asus', 'Model: ASUS F571LI\r\nIntel Core i5-10300H Processor (8M Cache, 2.5 GHz up to 4.5 GHz)\r\n8GB DDR4 RAM + 1TB HDD\r\nNvidia GTX 1650 Ti 4GB Graphics\r\n15.6\"(1920x1080) FHD LED-backlit Display', '0000-00-00', '0000-00-00'),
(2, 'Asus ZenBook 14 UX425JA Core i5 10th Gen 512GB SSD 14\" FHD Laptop with Windows 10', NULL, 'laptop/asus2.jpg', 'The compact, thin and ultralight all-metal design of ZenBook 14 makes it the ideal traveling companion. It\'s also the world\'s thinnest 14-inch laptop to feature a full set of I/O ports1 — including HDMI and USB Type-A — so you can enjoy versatile connectivity wherever you are. With ZenBook 14\'s amazing 22-hour battery life4, traveling without a charger isn\'t a big deal. When you do need to top up, its fast-charge feature can restore the battery to a 60% charge level in just 49 minutes, so you\'ll be ready to go in no time. Getting stuff done on the go is effortless with the elegant and lightweight ZenBook 14. ', 'Basic Information\r\nProcessor	Intel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\nDisplay	14.0-inch, LCD, FHD (1920 x 1080) 16:9, IPS-level Panel, Anti-glare display, LED Backlit, 300nits, sRGB: 100%, Screen-to-body ratio: 90%\r\nMemory	8GB LPDDR4X on board\r\nStorage	512GB M.2 NVMe PCIe 3.0 SSD\r\nGraphics	Intel UHD Graphics\r\nOperating System	Windows 10\r\nBattery	67WHrs, 4S1P, 4-cell Li-ion\r\nAdapter	TYPE-C, 65W AC Adapter, Output: 19V DC, 3.42A, 65W, Input: 100~240V AC 50/60Hz universal\r\nAudio	Smart Amp Technology\r\nBuilt-in array microphone\r\nharman/kardon (Mainstream)\r\nwith Cortana and Alexa voice-recognition support\r\nInput Devices\r\nKeyboard	Backlit Chiclet Keyboard\r\n1.4mm Key-travel\r\nWebCam	HD camera with IR function to support Windows Hello\r\nWithout privacy shutter\r\nCard Reader	Micro SD card reader\r\nNetwork & Wireless Connectivity\r\nWi-Fi	Intel WiFi 6 with Gig+ (802.11ax)\r\nBluetooth	Yes\r\nPorts, Connectors & Slots\r\nUSB (s)	1x USB 3.2 Gen 1 Type-A\r\n2x Thunderbolt 3 supports display / power delivery\r\nHDMI	Yes\r\nPhysical Specification\r\nDimensions (W x D x H)	319 x 208 x 13.9 ~ 13.9 mm\r\nWeight	1.17 kg\r\nColor(s)	Pine Gray\r\nWarranty\r\nManufacturing Warranty	02 years International Limited Warranty (Terms & condition Apply As Per Asus)', 90000, 97000, 'IN STOcK', 'ASULP89755', 'Asus', 'Model: Asus ZenBook 14 UX425JA i5\r\nIntel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\n8GB LPDDR4X RAM\r\n512GB PCIe NVMe M.2 SSD\r\n14” Full HD (1920 x 1080) Display', '0000-00-00', '0000-00-00'),
(3, 'ASUS VivoBook S15 S533JQ Core i7 10th Gen MX350 2GB Graphics 16GB RAM 15.6” FHD Laptop with Win 10', NULL, 'laptop/asus3.jpg', '\r\n\r\nThis multi function extreme durable device comes with 02 years International Limited Warranty (Terms & condition Apply As Per Asus)', 'Basic Information\r\nProcessor	Intel Core i5-10300H Processor (8M Cache, 2.5 GHz up to 4.5 GHz)\r\nDisplay	15.6\" FHD (1920x1080) LED-backlit (16:9), 60Hz Anti-Glare Panel with 45% NTSC Display with wide 178° viewing angles\r\nMemory	8GB DDR4 2666MHz RAM (4GB x 2)\r\nStorage	1TB HDD\r\nGraphics	Nvidia GeForce GTX 1650Ti with 4GB GDDR6 Graphics\r\nOperating System	Windows 10\r\nBattery	3 -Cell 42 Wh Polymer Battery\r\nAdapter	Plug type :ø4.5 (mm)\r\nOutput :\r\n19 V DC, 7.89 A, 150 W\r\nInput :\r\n100 -240 V AC, 50/60 Hz universal\r\nSpecial Feature	Back-lit Keyboard\r\nFinger Print Sensor\r\nInput Devices\r\nKeyboard	Back-lit Keyboard\r\nWebCam	HD\r\nNetwork & Wireless Connectivity\r\nWi-Fi	Integrated Wi-Fi 6 (802.11 ax (2x2)\r\nBluetooth	Bluetooth 5.0\r\nPorts, Connectors & Slots\r\nUSB (s)	1 x Type-C USB 3.0 (USB 3.1 Gen 1)\r\n1 x Type-A USB 3.0 (USB 3.1 Gen 1)\r\n2 x USB 2.0 port(s)\r\n1 x RJ45 LAN jack for LAN insert\r\nHDMI	1 x HDMI\r\nAudio Jack Combo	1 x Combo audio jack\r\nExtra RAM Slot	Yes (Up to max.20GB)\r\nExtra M.2 Slot	Yes\r\nSupported SSD Type	M.2 NVMe\r\nPhysical Specification\r\nDimensions (W x D x H)	359 x 248 x 21.9 mm\r\nWeight	2.14 g with battery\r\nColor(s)	Star Black\r\nWarranty\r\nManufacturing Warranty	02 Year International Limited Warranty (Terms & condition Apply As Per Asus)', 90000, 94000, 'IN STOCK', 'ASULP88774', 'Asus', 'Model: ASUS F571LI\r\nIntel Core i5-10300H Processor (8M Cache, 2.5 GHz up to 4.5 GHz)\r\n8GB DDR4 RAM + 1TB HDD\r\nNvidia GTX 1650 Ti 4GB Graphics\r\n15.6\"(1920x1080) FHD LED-backlit Display', '0000-00-00', '0000-00-00'),
(4, 'Asus ROG Strix G512LI Core i5 10th GTX 1650Ti Graphics 15.6\" FHD Laptop with Windows 10', NULL, 'laptop/asus4.jpg', 'The compact, thin and ultralight all-metal design of ZenBook 14 makes it the ideal traveling companion. It\'s also the world\'s thinnest 14-inch laptop to feature a full set of I/O ports1 — including HDMI and USB Type-A — so you can enjoy versatile connectivity wherever you are. With ZenBook 14\'s amazing 22-hour battery life4, traveling without a charger isn\'t a big deal. When you do need to top up, its fast-charge feature can restore the battery to a 60% charge level in just 49 minutes, so you\'ll be ready to go in no time. ', 'Basic Information\r\nProcessor	Intel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\nDisplay	14.0-inch, LCD, FHD (1920 x 1080) 16:9, IPS-level Panel, Anti-glare display, LED Backlit, 300nits, sRGB: 100%, Screen-to-body ratio: 90%\r\nMemory	8GB LPDDR4X on board\r\nStorage	512GB M.2 NVMe PCIe 3.0 SSD\r\nGraphics	Intel UHD Graphics\r\nOperating System	Windows 10\r\nBattery	67WHrs, 4S1P, 4-cell Li-ion\r\nAdapter	TYPE-C, 65W AC Adapter, Output: 19V DC, 3.42A, 65W, Input: 100~240V AC 50/60Hz universal\r\nAudio	Smart Amp Technology\r\nBuilt-in array microphone\r\nharman/kardon (Mainstream)\r\nwith Cortana and Alexa voice-recognition support\r\nInput Devices\r\nKeyboard	Backlit Chiclet Keyboard\r\n1.4mm Key-travel\r\nWebCam	HD camera with IR function to support Windows Hello\r\nWithout privacy shutter\r\nCard Reader	Micro SD card reader\r\nNetwork & Wireless Connectivity\r\nWi-Fi	Intel WiFi 6 with Gig+ (802.11ax)\r\nBluetooth	Yes\r\nPorts, Connectors & Slots\r\nUSB (s)	1x USB 3.2 Gen 1 Type-A\r\n2x Thunderbolt 3 supports display / power delivery\r\nHDMI	Yes\r\nPhysical Specification\r\nDimensions (W x D x H)	319 x 208 x 13.9 ~ 13.9 mm\r\nWeight	1.17 kg\r\nColor(s)	Pine Gray\r\nWarranty\r\nManufacturing Warranty	02 years International Limited Warranty (Terms & condition Apply As Per Asus)', 90000, 97000, 'IN STOcK', 'ASULP89755', 'Asus', 'Model: Asus ZenBook 14 UX425JA i5\r\nIntel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\n8GB LPDDR4X RAM\r\n512GB PCIe NVMe M.2 SSD\r\n14” Full HD (1920 x 1080) Display', '0000-00-00', '0000-00-00'),
(5, 'HP 15S-DU1067TU Celeron N4020 15.6 Inch HD Laptop with Windows 10', NULL, 'laptop/HP1.jpg', 'HP 15S-DU1067TU Laptop with Intel Celeron N4020 (1.1 GHz base frequency, up to 2.8 GHz burst frequency, 4 MB cache, 2 cores). This American stylish brand also contains 1TB storage and 4 GB DDR4 RAM to ensure greater compatibility. In addition, it has Intel UHD Graphics, windows 10 operating system, full-size island-style keyboard and HP TrueVision HD camera with integrated digital microphone. Its 3-cell, 41 Wh Li-ion batteries will provide longer power backup on travelling and the weight of only 1.77 kg will ensure the comfort while carrying. This multifunction extreme durable device comes with 1 Year International Warranty facility.', 'Basic Information\r\nProcessor	Intel Celeron N4020 Processor (4MB Cache, 1.1GHz up to 2.8GHz)\r\nDisplay	15.6\" HD LED (1360x768) Display\r\nMemory	4GB DDR4 RAM\r\nStorage	1TB HDD\r\nGraphics	Intel UHD Graphics 600\r\nOperating System	Windows 10\r\nBattery	41 Wh Li-ion batteries\r\nAdapter	Yes\r\nInput Devices\r\nKeyboard	Yes\r\nWebCam	Yes\r\nNetwork & Wireless Connectivity\r\nLAN	Yes\r\nWi-Fi	Yes\r\nBluetooth	Yes\r\nPorts, Connectors & Slots\r\nUSB (s)	Yes\r\nExtra RAM Slot	No Slots\r\nExtra M.2 Slot	No Slots\r\nPhysical Specification\r\nWeight	1.7Kg\r\nColor(s)	Black\r\nWarranty\r\nManufacturing Warranty	1 Year', 32500, 34940, 'OUT OF STOCK', 'HPLP88775', 'Hp', 'Model: HP 15S-DU1067TU\r\nIntel Celeron N4020 Processor (4MB Cache, 1.1GHz up to 2.8GHz)\r\n4GB DDR4 RAM\r\n1TB HDD\r\n15.6\" HD (1366x768) Display', NULL, NULL),
(6, 'Dell Latitude 3510 Core i3 10th Gen 15.6\" HD Laptop', NULL, 'laptop/dell1.jpg', 'Dell Latitude 3510 Laptop comes with Intel Core i3-10110U Processor (4M Cache, 2.10 GHz up to 4.10 GHz), 4GB DDR4 RAM, 256GB SSD and Integrated Intel UHD Graphics. The new Latitude 3510 is smaller and thinner, with a lighter finish and narrow screen bezels to give you more room to work. It also featured with a fingerprint reader built into the power button. Keep working with outstanding battery life. The laptop is also designed with Backlit Keyboard, User-Facing: 0.9 MP (720p) Web Cam, 4 Cell 53Whr ExpressCharge Capable Battery, Universal Audio Jack and also here 2 x USB Type-A (USB 3.1 / USB 3.2 Gen 1), 1 x USB Type-A (USB 2.0), 1 x USB 3.1 / USB 3.2 Gen 1 (Supports DisplayPort and Power Delivery), 1 x 1/8\" / 3.5 mm Headphone/Microphone Input/ Output ports are available. This laptop is compatible with more monitors and accessories, with a full range of available ports, including USB Type-C and legacy ports like HDMI and RJ45.', 'Basic Information\r\nProcessor	Intel Core i3-10110U Processor (4M Cache, 2.10 GHz up to 4.10 GHz)\r\nDisplay	15.6\" HD (1366 x 768) Display, Anti-Glare Non-Touch, Camera & Microphone, WLAN Capable\r\nMemory	4GB DDR4 RAM\r\nStorage	256GB SSD\r\nGraphics	Integrated Intel UHD Graphics\r\nOperating System	Free DOS\r\nBattery	4 Cell 53Whr ExpressCharge Capable Battery\r\nAdapter	65 Watt AC adapter\r\nAudio	Universal Audio Jack\r\nInput Devices\r\nKeyboard	Backlit Keyboard\r\nWebCam	User-Facing: 0.9 MP (720p) WebCam\r\n\r\nNetwork & Wireless Connectivity\r\nLAN	1 x RJ45 (Gigabit)\r\nWi-Fi	Wi-Fi 6 (802.11ax); Dual-Band (2.4 & 5 GHz)\r\nBluetooth	Bluetooth 5.1\r\nPorts, Connectors & Slots\r\nUSB (s)	Ports:\r\n2 x USB Type-A (USB 3.1 / USB 3.2 Gen 1)\r\n1 x USB Type-A (USB 2.0)\r\nUSB Type-C Ports:\r\n1 x USB 3.1 / USB 3.2 Gen 1 (Supports DisplayPort and Power Delivery)\r\nHDMI	1 x HDMI 1.4 Output\r\nAudio Jack Combo	1 x 1/8\" / 3.5 mm Headphone/Microphone Input/Output\r\nPhysical Specification\r\nDimensions (W x D x H)	Width: 14.23\" (361.40 mm) x Depth: 9.76\" (247.85 mm) x Height: 0.71\" (17.97 mm) |\r\nWeight	Starting Weight: 4.2 lb (1.9 kg)\r\nColor(s)	Black\r\nWarranty\r\nManufacturing Warranty	03 Year Warranty', 49000, 52000, 'OUT OF STOCK', 'Dell77854s', 'Dell', 'Model: Dell Latitude 3510 i3\r\nInte Core i3-10210U Processor (6M Cache, 2.10 GHz up to 4.10 GHz)\r\n4GB DDR4 RAM\r\n256GB SSD\r\n15.6\" HD (1366 x 768) Display', NULL, NULL),
(7, 'Lenovo IdeaPad S145 Core i3 8th Gen 15.6\" HD Laptop with Windows 10', NULL, 'laptop/lenovo1.jpg', 'Lenovo IdeaPad S145 Laptop comes with Intel Core i3-8130U Processor (4M Cache, 2.20 GHz up to 3.40 GHz), 4GB DDR4 RAM, 1TB HDD, Intel UHD Graphics 620 and Windows 10. This laptop also featured with 35 Whr, 2 Cell Li-Polymer battery which provides Up to 6 hours back up, 2 x 1.5W, Dolby Audio speaker system, SD card reader, Standard keyboard. Here 802.11 AC 1x1 Wi-Fi and Bluetooth 4.2 Network & Wireless Connectivity are available. Here is also 2x USB-A 3.1 Gen 1, 1x USB-A 2.0, HDMI, Headphone / mic combo are available. This IdeaPad S145 Laptop has 02 years International Limited Warranty (Terms & condition Apply As Per Lenovo).', 'Basic Information\r\nProcessor	Intel Core i3-8130U Processor (4M Cache, 2.20 GHz up to 3.40 GHz)\r\nDisplay	15.6\" HD (1366 x 768) Display\r\nMemory	4GB DDR4 RAM\r\nStorage	1TB HDD\r\nGraphics	Intel UHD Graphics 620\r\nOperating System	Windows 10\r\nBattery	Up to 6 hours w/ polymer 35 Whr, 2 Cell Li-Polymer\r\nAdapter	45W Adapter\r\nAudio	2 x 1.5W, Dolby Audio speaker system\r\nInput Devices\r\nKeyboard	Standard keyboard\r\nOptical Drive	No\r\nWebCam	HD Webcam\r\nCard Reader	SD card reader\r\nNetwork & Wireless Connectivity\r\nWi-Fi	802.11 AC 1x1\r\nBluetooth	Bluetooth 4.2\r\nPorts, Connectors & Slots\r\nUSB (s)	2x USB-A 3.1 Gen 1\r\n1x USB-A 2.0\r\nHDMI	Yes\r\nAudio Jack Combo	Headphone / mic combo\r\nExtra RAM Slot	Yes (Upgrade up to 8GB)\r\nExtra M.2 Slot	Yes\r\nSupported SSD Type	M.2 NVME PCIe\r\nPhysical Specification\r\nDimensions (W x D x H)	Starting at 327.1mm x 241mm x 19.9mm / 12.9″ x 9.5″ x 0.8″\r\nWeight	Starting at 1.6kg / 3.5lbs\r\nColor(s)	Black\r\nWarranty\r\nManufacturing Warranty	2 years International Limited Warranty (Terms & condition Apply As Per Lenovo)', 41000, 43900, 'IN STOCK', 'LENOLEP78557', 'Lenovo', 'Model: IdeaPad S145\r\nIntel Core i3-8130U Processor (4M Cache, 2.20 GHz up to 3.40 GHz)\r\n4GB DDR4 RAM\r\n1TB HDD\r\n15.6\" HD (1366 x 768) Display', NULL, NULL),
(8, 'Acer Aspire A514-53 Core i5 10th Gen 14\" Full HD Laptop with Genuine Windows 10', NULL, 'laptop/acer1.jpg', 'Nomadic with its battery life of 9 hours, the new thin and silver Ultrabook Acer Aspire A514-53 with 14 inch IPS Full HD anti-reflective screen benefits from fast SSD storage for enhanced responsiveness. Powerful in current use with its Quad Core i5 Whiskey Lake processor and its good amount of RAM, it has Wi-Fi ax and USB 3.1 Type-C connectivity. With its Silver brushed metal finish, it sports a rather sober and elegant design. Connectivity side, this Ultrabook is well equipped with its USB 3.1 Type-C, its wireless Wi-Fi ax modules ( newer and more efficient than Wi-Fi ac ) and Bluetooth 5.0 for remote connections and communications, its output Convenient HDMI video for easy connection to a TV or monitor, for example, its Ethernet and audio ports, not to mention its 3 USB all compatible with both USB 2.0 and USB 3.0, USB 3.0 ensuring transfers up to 10 times faster than USB 2.0 if USB 3.0 devices are connected to it. ', 'Basic Information\r\nProcessor	Intel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\nDisplay	14\" (35.6 cm) Full HD (1920 x 1080) ComfyView LED In-plane Switching (IPS) Technology\r\nMemory	8GB DDR4 SDRAM (4GB on board + 4GB on extra RAM slot)\r\nStorage	512 GB SSD\r\nGraphics	Intel UHD Graphics\r\nOperating System	Windows 10\r\nBattery	Lithium Ion Battery\r\nAdapter	45 W\r\nAudio	2 Stereo speakers\r\nInput Devices\r\nKeyboard	Backlit Keyboard\r\nWebCam	Yes\r\nNetwork & Wireless Connectivity\r\nLAN	Network (RJ-45): Yes\r\nGigabit Ethernet\r\nWi-Fi	IEEE 802.11 a/b/g/n/ac/ax\r\nBluetooth	Bluetooth 5.0\r\nPorts, Connectors & Slots\r\nUSB (s)	Total Number of USB Ports: 3\r\nUSB Type-C: Yes\r\nUSB Type-C Detail: USB Type-C port: USB 3.2 Gen 1 (up to 5 Gbps)\r\nHDMI	Yes\r\nAudio Jack Combo	Yes\r\nExtra RAM Slot	Yes (already 4GB RAM included in Extra slot)\r\n\r\nNote: upgrade total up to 12GB RAM\r\nPhysical Specification\r\nDimensions (W x D x H)	17.95 x 328.8 x 236 mm\r\nWeight	1.70 kg\r\nColor(s)	Silver\r\nWarranty\r\nManufacturing Warranty	2 Years', 67600, 73500, 'IN STOCK', 'ACLAP87977', 'Acer', 'Model: Acer Aspire A514-53\r\nIntel Core i5-1035G1 Processor (6M Cache, 1.00 GHz up to 3.60 GHz)\r\n8GB DDR4 RAM\r\n512GB SSD\r\n14\" FHD (1920 x 1080)IPS Display', NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `desktop`
--
ALTER TABLE `desktop`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `laptop`
--
ALTER TABLE `laptop`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `desktop`
--
ALTER TABLE `desktop`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `laptop`
--
ALTER TABLE `laptop`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
